on: push

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.6"

      - name: Install, build and test
        run: |
          npm i
          npm run build
          npm run test
